version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - td_options_analysis_DB__uri=postgresql://postgres:postgres@db:5432/td_options_analysis
      - td_options_analysis_DB__connect_args={}
    volumes:
      - .:/home/app/web
    depends_on:
      - db
  db:
    build: postgres
    image: td_options_analysis_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/td_options_analysis_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DBS=td_options_analysis, td_options_analysis_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
